development:
  adapter: postgresql
  database: drcourter
  host: localhost
  port: 5432
test:
  adapter: postgresql
  database: drcourter_test
production:
  adapter: postgresql
  database: drcourter
  host: localhost
