# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c59bae96b5c024ae0f85ac0b220e4f76fb83c1909130da4856890257962e448836a98e83468cf2f4022618bb41a97a036579674999135daac11bc8e27d138240

test:
  secret_key_base: e6779e74d75a4d22d0282f54893cadba738377026bfb5e15fa6747079bb5c4fb25f90f10ce0f5c849ae7360c937c6e41099627dd38525b0837ba1f20a97504b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
